import json
import os

NODES_INFO = json.loads(os.environ["NODES_INFO"])
NODE_ONE_ETH_SIGNER = os.environ["NODE_ONE_ETH_SIGNER"]
NODE_ONE_URL = os.environ["NODE_ONE_URL"]
RECOVERY_SERVICE_URL = os.environ["RECOVERY_SERVICE_URL"]
BACKUPS_SERVICE_URL = os.environ["BACKUPS_SERVICE_URL"]
IDCHAIN_RPC_URL = os.environ["IDCHAIN_RPC_URL"]
RECEIVER_BORDER = int(os.environ["RECEIVER_BORDER"])
SCORER_BORDER = int(os.environ["SCORER_BORDER"])
BALANCE_BORDER = int(os.environ["BALANCE_BORDER"])
BACKUP_BORDER = int(os.environ["BACKUP_BORDER"])
SPONSORSHIPS_UPDATE_BORDER = int(os.environ["SPONSORSHIPS_UPDATE_BORDER"])
APPS_UPDATE_BORDER = int(os.environ["APPS_UPDATE_BORDER"])
SEED_GROUPS_UPDATE_BORDER = int(os.environ["SEED_GROUPS_UPDATE_BORDER"])
SNAPSHOT_PERIOD = int(os.environ["SNAPSHOT_PERIOD"])
CHECK_INTERVAL = int(os.environ["CHECK_INTERVAL"])
MAX_RETRIES = int(os.environ["MAX_RETRIES"])
REDIS_HOST = os.environ["REDIS_HOST"]
REDIS_PORT = int(os.environ["REDIS_PORT"])
